### ISSUE TITLE
[Sub-Issue] Designing `arguments` format in YAML

### ISSUE THREAD

**Issue by fuyalasmit** [accordproject/concerto#1030]
## [Sub-Issue] Designing `arguments` format in YAML: Handling edge cases via implicit or explicit typing

This is a sub-issue of [#1024: Finalizing custom YAML format for DCS JSON <-> YAML Converter](https://github.com/accordproject/concerto/issues/1024)   

---

## Problem

In DCS JSON, `arguments` are represented with a `$class` and a `value`, like:

```json
"arguments": [
  {
    "$class": "concerto.metamodel@1.0.0.DecoratorString",
    "value": "inputType"
  },
  {
    "$class": "concerto.metamodel@1.0.0.DecoratorBoolean",
    "value": true
  },
  {
    "$class": "concerto.metamodel@1.0.0.DecoratorString",
    "value": "true"
  }
]
```

To convert this into a cleaner YAML format, the first approach is to use:

### 1. **Implicit Typing (Minimal YAML)**

```yaml
arguments:
  - value: inputType
  - value: true
  - value: "true"
```
This leverages YAML's built-in type inference to keep format minimal and readable.
However, there's an **edge case**:
In YAML, a logically string value that looks like boolean or number (e.g. "true", "4.5") must be quoted (`" "`) to avoid type misinterpretation.
While it helps for round trip conversion, it creates more confusion because of quotes `" "`

####  Optional Enhancement:
Force all string values to be quoted, regardless of content:

```yaml
arguments:
  - value: "inputType"
  - value: "true"
  - value: "3.4"
```
But quotes may add visual noise or redundancy.

---

### 2. **Explicit Typing with `type` + `value`**

To address the above discussed edge case more robustly, we can include an explicit `type` and `value` for each argument:
```yaml
arguments:
  - type: String
    value: inputType
  - type: Boolean
    value: true
  - type: String
    value: true
```

This avoids type confusion and quoting issues (`" "`), making it clearer for safe round trip conversion at the cost of slight verbosity.

---

#### Which could be the best one to go for ?

I recommend we adopt the **explicit typing** format for the following reasons:

- **Clarity** : Provides better understanding for human readers.
- **Robustness** : Handles edge cases more effectively.
- **Safety** : Enables safer parsing and validation logic.
