### ISSUE TITLE
Mechanism to define human-readable labels for model elements

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#360]
# Feature Request 🛍️
For use cases that create user interfaces from models it is necessary to define human-readable labels for model elements (concepts and properties).

## Use Case
Provide a mechanism to define natural language labels for model elements, supporting a variety of locales.

## Possible Solutions
1. Define a standard set of decorators to capture labels. E.g. `@label("en", "My Fancy Concept")`
2. Define a sidecar **vocabulary** file to store labels outside of the model file. E.g.

org.acme_en.voc (a yaml file):

``` yaml
Address:      Street Address
properties:
    line1:    First line of street address
    line2:    Second line of street address
    city:     City or Town
    county:   County name
    state:    State or region name
    postCode: Postal or Zip code
    country:  Country code
```

## Context
This feature would be used by form generators as well as the parser generator (e.g. for enumerated values), allowing natural language labels to be used, rather than the technical model element names.

## Detailed Description

On balance I favour the sidecar yaml file proposal as it ensures that the model doesn't get cluttered with decorators, especially if the model needs to support multiple locales. The yaml file is also easier (and less risky) to send for translation to external translation companies.

We would need to add `VocabularyManager` API to load a set of `voc` files for a set of locales  and to validate them against the models (no extra keys), and add utilities to load the label for a given locale for a model element.
