### ISSUE TITLE
Vocabulary auto generated for $identifier

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/concerto#776]
# Bug Report 🐛

Vocabulary auto generated for $identifier

## Expected Behavior
Should not auto generate vocabulary for $identifier

## Current Behavior
For the following model 
```
namespace org.acme@1.0.0

concept Person identified {
	o String name
}

enum Color {
    o RED
    o BLUE
    o GREEN
}

asset Vehicle identified by vin {
    o String vin
    o Color color
}

asset Truck extends Vehicle {
    o Double weight
}
```

Following auto gen vocab is found
```
#Generated vocabulary for namespace: org.acme@1.0.0
locale: en
namespace: org.acme@1.0.0
declarations:
  - Person: Person
    properties:
      - $identifier: Identifier of the Person # should not be auto generated
      - name: Name of the Person
  - Color: Color
    properties:
      - RED: RED of the Color
      - BLUE: BLUE of the Color
      - GREEN: GREEN of the Color
  - Vehicle: Vehicle
    properties:
      - vin: Vin of the Vehicle
      - color: Color of the Vehicle
  - Truck: Truck
    properties:
      - weight: Weight of the Truck
```

## Possible Solution

Fix bug in vocab visitor in codegen

## Steps to Reproduce

1. `concerto compile --target vocabulary` for the above `.cto` file

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]
