### ISSUE TITLE
Vocabularies don't support namespace-scoped decorators

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/concerto#858]
# Bug Report 🐛

The following model definition is valid...
```cs
@Term("My HR Model")
@Term_description("Reusable data definitions for the HR department.")
namespace acme.hr@1.0.0
```

When applying the `extract-decorators` command
```bash
concerto extract-decorators --model hr.cto --removeDecoratorsFromSource 
```
Produces a vocabulary file:
```yaml
locale: en
namespace: acme.hr@1.0.0
declarations:
  - : My HR Model
    description: Reusable data definitions for the HR department.
```

## Expected Behavior
I would expect a vocabulary file such as this:
```yaml
locale: en
namespace: acme.hr@1.0.0
term: My HR Model
description: Reusable data definitions for the HR department.
declarations:
   ...
```

## Possible Solution
1. The `@accordproject/concerto-vocabulary` package should be updated to support namespace-scoped decorators
