### ISSUE TITLE
If a declaration is named "properties" then we can't write a valid vocabulary for it

### ISSUE THREAD

**Issue by jamieshorten** [accordproject/concerto#982]
# Bug Report 🐛
If we have a model like
```
@Test2('world')
namespace com.example.e2e.a@1.0.1
@Term('A nice properties term')
concept properties {
  @Term('A cool string')
  o String someString
}
```
and run `concerto extract-decorators --models MODEL.cto --removeDecoratorsFromSource true` we get the following `vocabulary.yml`:
```
locale: en
namespace: com.example.e2e.a@1.0.1
declarations:
  - properties: A nice properties term
    properties:
      - someString: A cool string
```
Correct me if I'm missing something but that is an invalid YAML file due to the duplicated `properties` key. Trying to apply this vocab gives:
```
concerto decorate --models com.example.e2e.a.cto --vocabulary vocabulary_0.yml
10:29:53 - ERROR: YAMLParseError: Map keys must be unique at line 5, column 5:

  - properties: A nice properties term
    properties:
```

## Expected Behavior
I'm not sure how/if we should handle this case or if there is a way to write a vocab for the `properties` concept in the above model.
